use crate::components::CallStats;
use egui::ColorImage;
use std::path::PathBuf;

/// Events generated by the Logic Thread (Logic -> Controller)
/// These are "results" of completed work.
/// Note: WebRTC connections are managed internally by Logic Thread,
/// not sent back to UI Thread.
#[derive(Debug)]
pub enum LogicEvent {
    // --- RoomSetup ---
    OfferGenerated(String),  // SDP only, connection stays in Logic Thread
    AnswerGenerated(String), // SDP only, connection stays in Logic Thread
    ConnectionReady,         // Signals connection is ready, actual connection in Logic Thread

    // --- Room ---
    LocalFrame(ColorImage),
    RemoteFrame(ColorImage),
    CameraStarted,
    CameraStopped,
    RemoteCameraOn,
    RemoteCameraOff,
    AudioStarted,
    AudioMuted,
    AudioUnmuted,
    RemoteAudioOn,
    RemoteAudioOff,
    RemoteAudioMuted,
    RemoteAudioUnmuted,
    RemoteParticipantName(String),
    ParticipantDisconnected,
    OwnerDisconnected,
    StatsUpdated(CallStats), // Real-time statistics from WebRTC connection
    Error(String),

    // --- File Transfer ---
    FileChannelReady,
    /// Incoming file offer from peer
    FileOfferReceived {
        transfer_id: u64,
        filename: String,
        size: u64,
    },
    FileTransferAccepted {
        transfer_id: u64,
    },
    FileTransferRejected {
        transfer_id: u64,
        reason: String,
    },
    FileTransferProgress {
        transfer_id: u64,
        bytes_transferred: u64,
        total_bytes: u64,
    },
    FileTransferCompleted {
        transfer_id: u64,
        path: PathBuf,
    },
    FileTransferFailed {
        transfer_id: u64,
        reason: String,
    },
}
